// The category taxonomy. Every connection lands in exactly one category,
// chosen by job function. Cross-cutting facts (FAANG, YC, seniority...) are
// tags, so a Google recruiter is a Recruiter *and* tagged FAANG.
//
// Rule strings are phrases. Weights: s = 10 (decisive), m = 6, w = 3 (hint),
// x = 1.5 (tie-breaker). Append ":N" to set an explicit weight.
// Longer phrases win over the words inside them, so "sales engineer" is Sales
// and never also counts as "engineer".
// Company rules (cs = 5, cm = 3.5, cw = 2) nudge ambiguous titles and classify
// connections whose title is blank.

export const CATEGORY_IDS = [
  "founders", "executives", "investors", "recruiting", "software", "data_ai",
  "it_security", "product", "design", "engineering", "research", "healthcare",
  "legal", "finance", "consulting", "sales", "marketing", "customer", "hr",
  "project", "operations", "education", "students", "media", "public",
  "real_estate", "services", "unspecified",
] as const;

export type CategoryId = (typeof CATEGORY_IDS)[number];

export interface CategoryDef {
  id: CategoryId;
  label: string;
  short: string;
  emoji: string;
  description: string;
  s?: string[];
  m?: string[];
  w?: string[];
  x?: string[];
  cs?: string[];
  cm?: string[];
  cw?: string[];
}

export const CATEGORIES: CategoryDef[] = [
  {
    id: "founders",
    label: "Founders & Entrepreneurs",
    short: "Founders",
    emoji: "🚀",
    description: "Founders, co-founders, business owners and self-employed builders.",
    s: [
      "founder:12", "co founder:12", "founding partner", "entrepreneur:11", "serial entrepreneur:12",
      "owner:11", "business owner", "agripreneur", "edupreneur", "technopreneur", "mompreneur", "wantrepreneur",
      "ecopreneur", "infopreneur", "startup owner", "co owner", "proprietor", "solopreneur", "founder ceo:12",
      "shop owner", "store owner", "franchise owner", "restaurant owner", "social entrepreneur:12",
      "fundador", "fundadora", "co fundador", "cofundadora", "fondateur", "fondatrice", "grunder",
      "gruender", "grunderin", "fondatore", "fondatrice", "oprichter", "socio fundador",
      "self employed:7", "founder in residence", "indie hacker", "building stealth",
    ],
    m: ["stealth", "stealth startup", "freelancer", "promoter", "franchisee", "venture builder", "startup founder:12", "empreendedor", "emprendedor", "entrepreneure"],
    w: ["freelance", "startup", "founding", "independent professional", "own business", "building"],
    cm: ["stealth", "stealth startup", "stealth mode", "self employed", "freelance", "own business", "self", "freelancer"],
  },
  {
    id: "executives",
    label: "C-Suite & Executives",
    short: "Executives",
    emoji: "👔",
    description: "CEOs, CXOs, presidents, managing directors, chairs and board members.",
    s: [
      "ceo", "cto", "cfo", "coo", "cmo", "cio", "ciso", "cpo", "cro", "cdo", "cxo", "chro", "cco",
      "cao", "cbo", "cso", "cgo", "cko", "chief executive officer", "chief technology officer",
      "chief operating officer", "chief financial officer", "chief marketing officer",
      "chief product officer", "chief revenue officer", "chief information officer",
      "chief data officer", "chief people officer", "chief human resources officer",
      "chief business officer", "chief strategy officer", "chief growth officer",
      "chief medical officer", "chief digital officer", "chief of staff", "chief:8", "president",
      "managing director", "executive director", "director general", "geschaftsfuhrer",
      "geschaeftsfuehrer", "directeur general", "pdg", "amministratore delegato", "presidente",
      "chairman", "chairperson", "chairwoman", "vice chairman", "whole time director",
      "board director", "non executive director", "independent director", "country head",
    ],
    m: ["board member", "board advisor:5", "general manager:6.5", "country manager", "managing partner", "md", "gm", "business head", "chair:4", "gerente general", "director ejecutivo"],
    w: ["vp", "vice president", "executive vice president", "senior vice president"],
    x: ["director", "head:1", "executive:1", "leadership:1"],
  },
  {
    id: "investors",
    label: "Investors & VCs",
    short: "Investors",
    emoji: "💰",
    description: "Venture capitalists, angels, PE investors, accelerators and family offices.",
    s: [
      "venture capitalist", "vc", "venture partner", "general partner", "limited partner",
      "angel investor", "investor", "angel", "entrepreneur in residence", "eir",
      "venture capital", "private equity", "growth equity", "venture scout", "syndicate lead",
      "seed investor", "startup investor", "impact investor", "vc analyst", "vc associate",
      "vc investor", "venture investor", "inversor", "inversionista", "investidor", "investisseur",
      "investment principal", "principal investor",
    ],
    m: ["investing", "venture", "family office", "fund manager", "investment associate:5",
      "investment professional", "investment director", "investment partner", "scout:4",
      "portfolio operations", "platform venture", "accelerator", "incubator", "angel network"],
    w: ["investment", "lp", "gp", "fund:2"],
    cs: [
      "venture", "venture capital", "vc", "angel network", "seed fund", "private equity",
      "family office", "techstars", "500 startups", "500 global", "sequoia", "sequoia capital",
      "peak xv", "andreessen horowitz", "a16z", "accel", "lightspeed", "benchmark capital",
      "greylock", "kleiner perkins", "index ventures", "general catalyst", "tiger global",
      "softbank", "insight partners", "founders fund", "khosla", "nea", "bessemer",
      "matrix partners", "elevation capital", "nexus venture partners", "blume", "kalaari",
      "chiratae", "first round", "antler", "entrepreneur first", "sands capital", "iron pillar",
      "stellaris", "prime venture partners", "3one4", "bain capital", "blackstone", "kkr",
      "carlyle", "warburg pincus", "tpg", "apollo global", "general atlantic", "temasek",
    ],
    cm: ["capital:3", "equity", "fund", "accelerator", "incubator", "angel", "y combinator", "yc"],
    cw: ["partner", "investment:1.5", "holding"],
  },
  {
    id: "recruiting",
    label: "Recruiters & Talent",
    short: "Recruiters",
    emoji: "🎯",
    description: "Recruiters, talent acquisition, sourcers, headhunters and staffing.",
    s: [
      "recruiter", "recruiting", "recruitment", "talent acquisition", "technical recruiter",
      "sourcer", "talent sourcer", "headhunter", "executive search", "talent partner",
      "talent specialist", "talent lead", "campus recruiter", "university recruiter", "staffing",
      "staffing specialist", "placement coordinator", "placement officer:8", "hr recruiter",
      "recruitment consultant", "recruiting coordinator", "talent scout:7", "rpo",
      "reclutador", "reclutadora", "reclutamiento", "recrutador", "recrutadora", "recruteur",
      "recruteuse", "personalvermittler", "talent hunter", "hiring specialist", "hiring partner",
    ],
    m: ["talent", "placement", "talent manager:5"],
    w: ["sourcing", "hiring:2", "hiring manager:2"],
    cs: ["staffing", "recruitment", "recruiting", "placement", "manpower", "executive search",
      "randstad", "adecco", "hays", "michael page", "teamlease", "robert half", "kelly services",
      "manpowergroup", "korn ferry", "spencer stuart", "heidrick", "quess", "ciel hr",
      "hirect", "naukri", "instahyre", "cutshort", "talent"],
  },
  {
    id: "software",
    label: "Software Engineering",
    short: "SWE",
    emoji: "💻",
    description: "Software, web, mobile and QA engineers, developers and engineering managers.",
    s: [
      "software engineer", "software developer", "software engineering", "sde", "swe", "sdet",
      "developer", "programmer", "coder", "web developer", "full stack", "front end", "back end",
      "mobile developer", "ios", "android", "application developer", "app developer",
      "game developer", "blockchain developer", "smart contract", "web3", "member technical staff",
      "mts", "engineering manager", "software architect", "software architecture",
      "principal engineer", "staff engineer", "distinguished engineer", "founding engineer",
      "forward deployed engineer", "embedded software", "firmware engineer", "firmware",
      "qa engineer", "software tester", "test automation", "automation tester",
      "salesforce developer", "tech lead", "technical lead", "product engineer",
      "developer advocate", "developer relations", "devrel", "software", "java", "python",
      "javascript", "typescript", "react", "nodejs", "golang", "php", "dotnet", "csharp", "cpp",
      "flutter", "kotlin", "ruby rails", "django", "angular", "vue", "sde intern",
      "desarrollador", "desarrolladora", "programador", "programadora", "desenvolvedor",
      "desenvolvedora", "developpeur", "developpeuse", "entwickler", "softwareentwickler",
      "sviluppatore", "ontwikkelaar", "programmeur", "ingenieur logiciel", "ingeniero software",
      "engenheiro software", "api", "web engineer", "open source contributor", "blockchain engineer", "solidity",
      "rust developer",
    ],
    m: ["systems engineer", "system engineer", "quality assurance", "test engineer", "automation engineer:5",
      "qa", "tester", "programming", "coding", "open source", "lead engineer", "technology analyst:5",
      "associate engineer", "engineer trainee:4", "application engineer:5", "web", "swift", "rust",
      "senior engineer", "engineering lead", "head engineering", "vp engineering", "director engineering"],
    w: ["engineer", "engineering", "hacker", "tech:2", "technology:2", "quality analyst:2.5"],
    x: ["technical"],
    cm: [
      "google", "alphabet", "microsoft", "amazon", "meta", "facebook", "apple", "netflix",
      "infosys", "tcs", "tata consultancy service", "wipro", "hcl", "hcltech", "cognizant",
      "tech mahindra", "ibm", "oracle", "sap", "salesforce", "adobe", "uber", "atlassian", "stripe",
      "github", "gitlab", "flipkart", "swiggy", "zomato", "razorpay", "paytm", "phonepe", "zoho",
      "freshworks", "ltimindtree", "mindtree", "mphasis", "persistent system", "epam",
      "thoughtworks", "globant", "linkedin", "twitter", "shopify", "spotify", "airbnb", "atlassian",
      "intuit", "servicenow", "workday", "vmware", "dropbox", "pinterest", "snap", "coinbase",
      "palantir", "doordash", "lyft", "zoom", "twilio", "mongodb", "bytedance", "tiktok", "meesho",
      "zepto", "cred", "ola", "byju", "juspay", "postman", "browserstack", "hasura", "sprinklr",
      "software", "infotech", "infosystem", "saas", "app",
    ],
    cw: ["technology", "tech", "lab", "system", "solution", "digital", "io", "it service", "consultancy service", "infoway", "softech", "soft"],
  },
  {
    id: "data_ai",
    label: "Data, AI & Analytics",
    short: "Data & AI",
    emoji: "🧠",
    description: "Data scientists, ML/AI engineers, analysts and BI professionals.",
    s: [
      "data scientist", "data science", "data analyst", "data engineer", "data engineering",
      "machine learning", "ml engineer", "mle", "ai engineer", "artificial intelligence",
      "deep learning", "nlp", "natural language processing", "computer vision",
      "applied scientist", "business intelligence", "bi analyst", "bi developer", "bi engineer",
      "analytics", "data analytics", "big data", "statistician", "analytics engineer", "mlops",
      "prompt engineer", "decision scientist", "data architect", "product analyst",
      "analytics manager", "data strategist", "ai ml", "ai specialist", "ml ops", "data",
      "cientifico datos", "analista datos", "ingeniero datos", "data lead", "head data",
      "generative ai", "genai", "llm:6", "reinforcement learning", "data mining", "data annotator",
      "data labeling", "ai trainer", "ai tutor", "ai research engineer", "business intelligence developer",
      "business intelligence engineer", "business intelligence analyst", "etl developer", "power bi developer",
      "tableau developer", "ml developer", "ai developer", "data developer", "ai ml developer", "sql developer:8",
      "data analysis", "computer vision engineer", "ai product engineer:6",
    ],
    m: ["ai", "ml", "etl", "tableau", "power bi", "powerbi", "sql", "reporting analyst", "insights",
      "business analyst:6", "mis:5", "mis executive", "quantitative:3", "research analyst:3"],
    w: ["analyst", "analytical", "statistic", "modeling", "modelling"],
    cs: ["openai", "anthropic", "deepmind", "google deepmind", "mistral", "cohere", "hugging face",
      "scale ai", "databricks", "snowflake", "mu sigma", "fractal analytics", "tiger analytics",
      "latentview", "perplexity", "xai", "character ai", "stability ai", "sarvam", "krutrim"],
    cm: ["analytics", "ai:3", "data:2.5", "intelligence:2"],
  },
  {
    id: "it_security",
    label: "IT, Cloud & Security",
    short: "IT & Security",
    emoji: "🛡️",
    description: "DevOps, SRE, cloud, networking, sysadmin, IT support and cybersecurity.",
    s: [
      "devops", "devops engineer", "site reliability", "sre", "cloud engineer", "cloud architect",
      "solutions architect", "solution architect", "infrastructure engineer", "platform engineer",
      "network engineer", "network administrator", "system administrator", "systems administrator",
      "sysadmin", "it administrator", "it support", "it manager", "it specialist", "it consultant",
      "it analyst", "it:8", "information technology", "helpdesk", "help desk", "desktop support",
      "technical support engineer", "cyber security", "information security", "infosec",
      "security engineer", "security analyst", "soc analyst", "penetration tester", "pentester",
      "ethical hacker", "security architect", "security consultant", "appsec",
      "application security", "cloud security", "database administrator", "dba", "sap consultant",
      "salesforce administrator", "salesforce consultant", "noc engineer", "it operation",
      "service desk", "enterprise architect", "enterprise architecture", "cloud architecture",
      "solution architecture", "technical architect", "erp consultant", "oracle consultant",
      "sap abap", "sap fico", "sap mm", "sap sd", "fico consultant", "abap consultant", "mm consultant",
      "sd consultant", "basis consultant", "sap fico consultant", "sap mm consultant", "sap sd consultant",
      "sap abap consultant", "sap basis consultant", "sap hana consultant", "sap hcm consultant", "sap pp consultant", "functional consultant:8", "workday consultant", "servicenow developer",
      "oracle fusion", "sap functional", "sap technical", "dynamics 365", "crm consultant:7", "vapt", "red team", "blue team", "security researcher",
      "threat intelligence", "incident response", "iam engineer", "identity access management",
      "kubernetes", "aws", "azure", "gcp", "cloud", "linux administrator", "informatico", "informatique",
      "technicien informatique", "tecnico informatico", "system engineer it",
    ],
    m: ["security:5", "erp", "sap", "servicenow", "linux", "network:4", "infrastructure:4", "mainframe",
      "citrix", "vmware", "support engineer:6", "grc:5", "architect:3", "reliability", "technical support:5.5",
      "it executive", "system analyst", "systems analyst", "it head", "edp"],
    cm: ["palo alto network", "crowdstrike", "fortinet", "cisco", "cloudflare", "zscaler", "okta",
      "rackspace", "nutanix", "red hat", "hashicorp", "datadog", "splunk", "cybersecurity",
      "cyber security", "network", "cloud", "infosec"],
    cw: ["security:1.5", "datacenter", "data center"],
  },
  {
    id: "product",
    label: "Product Management",
    short: "Product",
    emoji: "🧭",
    description: "Product managers, product owners, APMs and product leaders.",
    s: [
      "product manager", "product management", "product owner", "product lead", "head product",
      "vp product", "director product", "apm", "associate product manager",
      "technical product manager", "group product manager", "gpm", "product leader",
      "senior product manager", "principal product manager", "chef produit", "produktmanager",
      "gerente producto", "product strategy", "product operations", "product ops", "product intern",
      "product consultant:7", "product specialist:7", "product management intern",
    ],
    m: ["product:5", "pm:5", "product growth"],
    w: ["tpm", "roadmap"],
  },
  {
    id: "design",
    label: "Design & UX",
    short: "Design",
    emoji: "🎨",
    description: "Product, UX/UI, graphic, brand, industrial, fashion and interior designers.",
    s: [
      "designer", "design", "ux", "ui", "ui ux", "user experience", "user interface",
      "product designer", "graphic designer", "visual designer", "interaction designer",
      "ux researcher", "user researcher", "creative director", "motion designer", "3d designer",
      "fashion designer", "interior designer", "industrial designer", "game designer",
      "web designer", "brand designer", "design lead", "head design", "design manager",
      "content designer", "illustrator:8", "figma", "ux writer:8", "design thinking",
      "disenador", "disenadora", "graphiste", "designerin", "designer grafico", "art director:8",
      "visualizer", "visualiser", "ux ui", "product design", "communication designer",
      "service designer", "experience designer", "jewellery designer", "jewelry designer",
      "textile designer", "packaging designer", "typographer", "concept artist:7",
    ],
    m: ["creative:4", "canva", "photoshop"],
    cm: ["design", "ideo", "frog design", "creative:3"],
    cw: ["studio:1.5"],
  },
  {
    id: "engineering",
    label: "Hardware & Core Engineering",
    short: "Core Eng",
    emoji: "⚙️",
    description: "Mechanical, electrical, electronics, civil, chemical, aerospace, hardware & manufacturing engineers.",
    s: [
      "mechanical engineer", "mechanical", "electrical engineer", "electrical", "electronics engineer",
      "electronics", "civil engineer", "civil", "chemical engineer", "chemical", "aerospace engineer",
      "aerospace", "aeronautical", "automotive", "manufacturing engineer", "manufacturing",
      "process engineer", "quality engineer", "hardware engineer", "hardware", "embedded",
      "embedded system", "vlsi", "asic", "fpga", "rtl", "verification engineer",
      "design verification", "chip design", "analog design", "pcb", "semiconductor", "robotics",
      "mechatronics", "instrumentation", "control engineer", "controls engineer", "plc", "scada",
      "maintenance engineer", "field engineer", "structural engineer", "geotechnical",
      "environmental engineer", "petroleum engineer", "mining engineer", "metallurgical",
      "metallurgy", "materials engineer", "biomedical engineer", "nuclear engineer",
      "energy engineer", "power engineer", "renewable energy", "solar engineer", "hvac", "cad",
      "autocad", "solidworks", "catia", "ansys", "graduate engineer trainee", "get:3", "communication engineer", "communications engineer",
      "rf engineer", "telecom engineer", "telecommunication", "optical engineer", "photonics",
      "hardware design", "product design engineer", "design engineer", "tool design", "cnc",
      "machinist", "draftsman", "draughtsman", "project engineer", "chief engineer", "plant manager:8",
      "production engineer:7", "quality control:6", "qc engineer", "piping engineer",
      "process safety", "hse engineer", "safety engineer", "reliability engineer", "tool engineer",
      "electronic", "physical design", "silicon", "soc design", "dft engineer", "marine engineer",
      "automobile", "ev engineer", "battery engineer", "powertrain", "thermal engineer",
      "cae engineer", "cfd", "fea", "npd engineer", "r and d engineer", "rnd engineer",
      "ingenieur mecanique", "ingeniero mecanico", "ingeniero civil", "ingeniero industrial",
      "maschinenbau", "elektroingenieur", "industrial engineer", "production manager:6",
      "field application engineer", "validation engineer", "post silicon", "pre silicon", "test and measurement",
    ],
    m: ["technician:5", "rnd", "ingeniero:4", "engenheiro:4", "ingenieur:4", "quality:3", "production:4",
      "maintenance:4", "welder:4", "plant:4", "shop floor", "iot"],
    w: ["engineer:2.5", "engineering:2.5", "technical:1.5"],
    cm: [
      "motor", "automotive", "auto", "manufacturing", "industry", "steel", "energy", "power", "oil",
      "petroleum", "chemical", "aerospace", "semiconductor", "electronic", "electrical", "engineering",
      "tata steel", "reliance industry", "larsen toubro", "l t", "bosch", "siemens", "ge",
      "honeywell", "boeing", "airbus", "tesla", "spacex", "intel", "amd", "qualcomm",
      "texas instrument", "nxp", "analog device", "micron", "applied material", "asml", "tsmc",
      "samsung", "mahindra", "maruti suzuki", "tata motor", "hyundai", "toyota", "ford",
      "general motor", "abb", "schneider electric", "caterpillar", "cummin", "lockheed martin",
      "ongc", "bhel", "ntpc", "iocl", "indian oil", "shell", "bp", "exxonmobil", "chevron",
      "saudi aramco", "schlumberger", "halliburton", "hindalco", "vedanta", "jsw", "adani",
      "rolls royce", "safran", "thales", "3m", "emerson", "danfoss", "volvo", "bajaj auto",
      "hero motocorp", "ashok leyland", "tvs", "nvidia", "arm", "cadence", "synopsys", "broadcom",
      "marvell", "mediatek", "infineon", "stmicroelectronic", "renesas", "foxconn", "denso",
    ],
    cw: ["gas", "industrial", "machine", "machinery", "forge", "plastic", "polymer", "cement", "metal", "mining"],
  },
  {
    id: "research",
    label: "Research & Science",
    short: "Research",
    emoji: "🔬",
    description: "Researchers, scientists, PhD candidates, postdocs and R&D.",
    s: [
      "geoscientist", "geophysicist", "seismologist", "hydrologist", "oceanographer", "meteorologist",
      "researcher", "research scientist", "research engineer", "research associate",
      "research assistant", "research fellow", "postdoc", "postdoctoral", "post doctoral", "phd",
      "ph d", "phd candidate", "phd student", "phd scholar", "doctoral candidate",
      "doctoral student", "doctoral researcher", "research scholar", "scientist",
      "principal investigator", "research intern", "junior research fellow", "jrf", "srf",
      "senior research fellow", "physicist", "chemist", "biologist", "microbiologist",
      "biochemist", "geologist", "astronomer", "astrophysicist", "mathematician", "economist",
      "neuroscientist", "ecologist", "ai researcher", "ml researcher", "research student",
      "visiting scholar", "visiting researcher", "investigador", "investigadora", "pesquisador",
      "pesquisadora", "chercheur", "chercheuse", "doktorand", "doktorandin", "wissenschaftler",
      "wissenschaftlerin", "research lead", "research manager", "head research",
      "quantum", "bioinformatician", "bioinformatics", "computational biologist", "agronomist",
      "materials scientist", "lab manager", "laboratory manager", "scientific officer",
    ],
    m: ["research", "scientific", "laboratory", "scholar", "r and d", "lab assistant", "genomics:5", "lab:3"],
    w: ["fellow", "academic researcher", "lab"],
    cs: ["iisc", "iiser", "csir", "tifr", "max planck", "cnrs", "cern", "barc", "national laboratory",
      "fraunhofer", "inria", "riken", "allen institute", "howard hughes", "broad institute",
      "research institute", "institute science", "icmr", "icar", "ncbs"],
    cm: ["research", "laboratory", "lab:1.5"],
    cw: ["university:1.5", "college:1", "institute:1.5", "iit:1.5", "school:0.5"],
  },
  {
    id: "healthcare",
    label: "Healthcare & Life Sciences",
    short: "Healthcare",
    emoji: "🩺",
    description: "Doctors, nurses, pharmacists, therapists, clinical, pharma and biotech professionals.",
    s: [
      "doctor", "physician", "surgeon", "nurse", "registered nurse", "mbbs", "bds", "bams", "bhms",
      "dentist", "dental", "pharmacist", "pharmacy", "medical", "clinical", "clinician", "therapist",
      "physiotherapist", "physical therapist", "occupational therapist", "psychologist",
      "psychiatrist", "dietitian", "dietician", "nutritionist", "optometrist", "radiologist",
      "radiographer", "sonographer", "medical lab technician", "lab technician:6", "paramedic",
      "emt", "caregiver", "midwife", "cardiologist", "dermatologist", "pediatrician",
      "gynecologist", "gynaecologist", "oncologist", "neurologist", "orthopedic", "orthopaedic",
      "anesthesiologist", "anesthetist", "ophthalmologist", "resident doctor", "house officer",
      "medical officer", "healthcare", "health care", "clinical research", "clinical trial",
      "biotech", "biotechnology", "life science", "medical affairs", "medical science liaison",
      "pharmacovigilance", "veterinarian", "veterinary", "public health", "epidemiologist",
      "medical coder", "medical coding", "healthcare administrator", "hospital administrator",
      "mental health", "chiropractor", "audiologist", "speech therapist", "speech pathologist",
      "doula", "medico", "medica", "doctora", "enfermera", "enfermero", "enfermeira", "medecin",
      "infirmier", "infirmiere", "arzt", "arztin", "krankenschwester", "farmaceutico",
      "pharmaceutical", "pharma", "biomedical", "medical writer:8", "medical device", "counseling psychologist",
      "clinical psychologist", "psychotherapist", "homeopath", "ayurvedic", "ayurveda",
      "surgical", "icu", "hospitalist", "gp doctor", "family medicine", "internal medicine",
      "pathologist", "pathology", "phlebotomist", "optician", "dental hygienist", "nursing",
      "healthtech", "health tech", "patient care", "care coordinator", "hospital",
      "regulatory affairs:6", "drug safety", "drug discovery", "microbiology", "immunology",
      "nutrition coach", "nutrition", "consultant physician", "consultant surgeon", "medical consultant",
    ],
    m: ["health", "patient", "rn", "resident:4", "wellness:4", "vet", "drug", "medicine", "clinic", "genomics:5", "care assistant"],
    cs: ["hospital", "clinic", "healthcare", "medical", "pharma", "pharmaceutical", "biotech",
      "biotechnology", "therapeutic", "life science", "diagnostic", "bioscience", "medtech",
      "apollo hospital", "fortis", "max healthcare", "aiims", "manipal hospital", "narayana health",
      "medanta", "mayo clinic", "cleveland clinic", "kaiser permanente", "nhs", "pfizer",
      "novartis", "johnson johnson", "jnj", "gsk", "glaxosmithkline", "sanofi", "roche", "merck",
      "astrazeneca", "abbott", "eli lilly", "bristol myers squibb", "bayer", "moderna", "biocon",
      "sun pharma", "cipla", "dr reddy", "lupin", "zydus", "glenmark", "medtronic",
      "philips healthcare", "ge healthcare", "siemens healthineer", "iqvia", "labcorp",
      "thermo fisher", "illumina", "practo", "pharmeasy", "1mg", "healthify", "cult health",
    ],
    cm: ["health", "medicine", "care:1.5", "wellness"],
  },
  {
    id: "legal",
    label: "Legal & Compliance",
    short: "Legal",
    emoji: "⚖️",
    description: "Lawyers, counsel, paralegals, judges, compliance and IP professionals.",
    s: [
      "lawyer", "attorney", "advocate:8", "counsel", "legal counsel", "general counsel",
      "in house counsel", "associate counsel", "legal", "paralegal", "solicitor", "barrister",
      "judge", "magistrate", "notary", "legal advisor", "legal associate", "law clerk", "law",
      "compliance", "compliance officer", "company secretary", "contract manager", "patent",
      "patent agent", "trademark", "litigation", "intellectual property", "legal intern",
      "risk compliance", "abogado", "abogada", "advogado", "advogada", "avocat", "avocate",
      "rechtsanwalt", "rechtsanwaltin", "anwalt", "avvocato", "advocaat", "jurist", "juriste",
      "juridico", "juridique", "legal manager", "legal head", "legal officer", "llb:7",
      "arbitrator", "mediator:6", "public prosecutor", "prosecutor", "legal analyst",
      "contract specialist", "legal operation", "data protection officer", "dpo",
      "anti money laundering:6.5", "aml:6.5", "sanction", "regulatory compliance",
    ],
    m: ["regulatory", "contract", "privacy", "gdpr", "governance:5", "ethic", "grc:5", "legal tech"],
    w: ["llm:2.5"],
    cs: ["law", "legal", "law firm", "advocate", "attorney", "solicitor", "chamber", "law office",
      "cyril amarchand mangaldas", "amarchand", "azb", "trilegal", "khaitan", "shardul", "jsa",
      "luthra", "baker mckenzie", "latham watkins", "kirkland ellis", "skadden", "clifford chance",
      "allen overy", "linklaters", "freshfields", "dentons", "dla piper", "high court", "supreme court",
      "court", "legal service"],
    cw: ["llp:1.5"],
  },
  {
    id: "finance",
    label: "Finance, Banking & Accounting",
    short: "Finance",
    emoji: "🏦",
    description: "Bankers, accountants, auditors, analysts, traders, insurance and wealth management.",
    s: [
      "finance", "financial", "accountant", "accounting", "chartered accountant", "cpa", "cfa",
      "acca", "cma", "auditor", "audit", "internal audit", "tax", "taxation", "controller",
      "financial controller", "comptroller", "treasurer", "treasury", "bookkeeper", "bookkeeping",
      "investment banker", "investment banking", "banker", "banking", "bank", "equity research",
      "financial analyst", "fpa", "credit analyst", "credit manager", "risk analyst",
      "risk manager", "risk management", "underwriter", "underwriting", "actuary", "actuarial",
      "wealth manager", "wealth management", "private banker", "financial advisor",
      "financial adviser", "financial planner", "portfolio manager", "asset management",
      "asset manager", "hedge fund", "trader", "quant", "quantitative analyst",
      "quantitative researcher", "quantitative developer", "quant developer", "quant researcher",
      "capital market", "mna", "merger acquisition", "corporate finance", "valuation",
      "loan officer", "teller", "bank teller", "accounting payable", "accounting receivable",
      "cost accountant", "income tax", "tax consultant", "stock broker", "stockbroker",
      "finanza", "financa", "contador", "contadora", "contable", "comptable", "buchhalter",
      "buchhalterin", "wirtschaftsprufer", "contabilidad", "ca articleship", "articled assistant",
      "article assistant", "ca intern", "ca finalist", "ca inter", "semi qualified ca", "cs executive:4",
      "fund accountant", "fund accounting", "investment analyst", "credit risk", "market risk",
      "insurance", "insurance advisor:7", "claim", "claims adjuster", "billing specialist",
      "payroll accountant", "gst", "cost accounting", "equity analyst", "investment manager",
      "relationship manager:6.5", "branch manager:5", "loan", "mortgage advisor", "fintech:4",
      "payment:5", "crypto:5", "defi", "trading", "derivative", "fixed income", "forex",
      "commodity trader", "credit", "kyc:6", "collection:4", "recovery officer", "mutual fund", "ca final",
      "article trainee", "articleship", "fraud analyst", "fraud:6", "chargeback", "reconciliation",
    ],
    m: ["ca:3", "fund manager:7", "equity:4", "broker:5", "billing", "mortgage:5", "investment:3", "wealth", "stock", "economic:3"],
    w: ["blockchain:2"],
    x: ["analyst:2", "associate:0.8"],
    cs: [
      "bank", "banking", "financial", "finance", "securities", "insurance", "assurance",
      "life insurance", "wealth", "asset management", "credit", "lending", "loan", "payment",
      "fintech", "trading", "brokerage", "chartered accountant", "ca firm", "cpa", "audit",
      "goldman sachs", "jpmorgan", "jp morgan", "jpmorgan chase", "morgan stanley",
      "bank america", "citi", "citibank", "citigroup", "barclays", "hsbc", "deutsche bank", "ubs",
      "credit suisse", "wells fargo", "blackrock", "fidelity", "vanguard", "american express",
      "amex", "visa", "mastercard", "paypal", "capital one", "state street", "bny mellon",
      "northern trust", "charles schwab", "nomura", "mizuho", "bnp paribas", "societe generale",
      "standard chartered", "hdfc", "icici", "sbi", "state bank india", "axis", "kotak",
      "yes bank", "bajaj finserv", "bajaj finance", "lic", "jane street", "citadel", "two sigma",
      "de shaw", "d e shaw", "hudson river trading", "optiver", "tower research", "jump trading",
      "millennium", "bridgewater", "renaissance technology", "lazard", "evercore", "rothschild",
      "jefferies", "macquarie", "nuvama", "motilal oswal", "zerodha", "groww", "angel one",
      "bank baroda", "punjab national bank", "canara bank", "union bank", "indusind",
      "idfc", "au small finance", "rbl", "federal bank", "sbi life", "hdfc life", "icici prudential",
      "max life", "tata aia", "policybazaar", "allianz", "axa", "prudential", "metlife", "aig",
      "ing", "santander", "bbva", "rbc", "td bank", "scotiabank", "commonwealth bank", "anz",
      "westpac", "crisil", "moody", "s p global", "fitch", "icra", "mckinsey capital",
    ],
    cm: ["capital:2", "investment:3", "accountant", "tax", "fund:1.5", "treasury", "exchange:2", "finserv", "finvest"],
  },
  {
    id: "consulting",
    label: "Consulting & Strategy",
    short: "Consulting",
    emoji: "🧩",
    description: "Management & strategy consultants, advisors, business analysts and transformation.",
    s: [
      "founder office:14", "founders office:14", "office founder:14", "ceo office:13", "office ceo:13",
      "management consultant", "strategy consultant", "strategy", "business consultant",
      "associate consultant", "principal consultant", "engagement manager", "associate partner",
      "strategy analyst", "corporate strategy", "digital transformation", "change management",
      "independent consultant", "consulting", "consultancy", "strategic advisor", "strategy manager",
      "strategy associate", "business strategy", "strategy lead", "advisory", "transformation lead",
      "consultor", "consultora", "conseil", "berater", "beraterin", "consulente",
      "business analyst:7", "management trainee strategy",
    ],
    m: ["consultant:7", "advisor", "adviser", "transformation", "strategic:5", "partner:4.5", "expert:3",
      "process improvement:4"],
    w: ["principal:2", "subject matter expert"],
    x: ["associate:0.8"],
    cs: ["consulting", "consultant", "consultancy", "advisory", "advisor", "mckinsey", "boston consulting group",
      "bcg", "bain", "bain company", "deloitte", "pwc", "pricewaterhousecooper", "ey", "ernst young",
      "kpmg", "accenture", "capgemini", "oliver wyman", "kearney", "roland berger", "zs associate",
      "zs", "lek", "booz allen", "alvarez marsal", "fti consulting", "protiviti", "grant thornton",
      "bdo", "rsm", "mazars", "gartner", "everest group", "strategy", "redseer", "praxis global",
      "infosys consulting", "ibm consulting", "deloitte consulting", "ey parthenon", "monitor deloitte"],
    cw: ["partner:1.5", "associate:1"],
  },
  {
    id: "sales",
    label: "Sales & Business Development",
    short: "Sales",
    emoji: "📈",
    description: "Account executives, SDRs, business development, partnerships and pre-sales.",
    s: [
      "sale", "sales", "account executive", "key account manager", "key accounting manager",
      "business development", "bdr", "sdr", "bde", "bdm", "sales development representative",
      "inside sales", "sales engineer", "presales", "pre sale", "solutions engineer:8",
      "solutions consultant:7", "partnership", "partnership manager", "channel partner",
      "channel manager", "commercial manager", "territory manager", "client partner",
      "account director", "go market", "gtm", "retail sale", "sales associate",
      "sales representative", "telecaller", "telesales", "field sale", "medical representative",
      "business developer", "enterprise sale", "sale operation", "revops", "revenue operation",
      "strategic accounting", "enterprise accounting", "global accounting manager", "vendedor",
      "vendedora", "venta", "ventas", "vertrieb", "vertriebsleiter", "ejecutivo comercial",
      "ejecutiva comercial", "representante comercial", "alliance manager", "alliances",
      "customer acquisition", "insurance agent:8", "area manager sale", "distributor sale",
      "dealer manager", "franchise development", "bizdev", "lead generation:6", "sales intern", "software sale", "saas sale", "ad sale", "media sale",
      "account strategist:6", "growth partner", "commercial director", "revenue manager:6",
      "sales head", "export manager:6", "customer engineer:8", "partner manager", "partner development",
      "partnerships lead", "channel sales",
    ],
    m: ["commercial", "revenue", "account manager:6", "representante:5", "dealer:5", "distributor:4",
      "agent:3", "client:2", "trader:3"],
    w: ["growth:2", "b2b", "export:3", "merchandiser:2"],
    x: ["executive:1.2"],
    cw: ["sale:2", "distributor", "dealer", "trading company:2", "enterprise:1", "export", "import"],
  },
  {
    id: "marketing",
    label: "Marketing & Communications",
    short: "Marketing",
    emoji: "📣",
    description: "Marketers, growth, brand, content, SEO, social, PR and communications.",
    s: [
      "marketing", "marketer", "digital marketing", "growth marketing", "growth marketer",
      "product marketing", "performance marketing", "content marketing", "seo", "sem:5", "ppc",
      "social media", "social media manager", "brand manager", "branding", "communication",
      "public relation", "corporate communication", "copywriter:8", "content strategist:7",
      "email marketing", "marketing automation", "demand generation", "demand gen",
      "growth hacker", "growth manager", "growth lead", "head growth", "advertising", "media buyer",
      "media planner", "influencer marketing", "brand ambassador", "market research",
      "creative strategist", "mercadotecnia", "comunicacion", "mercadeo", "relaciones publica",
      "kommunikation", "marketing intern", "community manager", "community lead", "brand strategist",
      "crm manager:6", "lifecycle marketing", "retention marketing", "event manager:7",
      "event management", "events:5", "campaign manager", "ad operation:6", "affiliate marketing",
      "evangelist:6", "spokesperson", "media relation", "pr manager", "pr executive", "brand",
      "growth hacking", "seo specialist", "sem specialist", "social media executive", "digital marketer",
      "marketing communication", "press officer", "public affair:6", "category manager:5",
      "ecommerce manager", "e commerce manager", "marketplace manager", "trade marketing",
    ],
    m: ["campaign", "pr", "affiliate", "community:4", "growth:4", "market:3", "promotion", "outreach:4"],
    x: ["digital", "content:1.2", "creative:1.5"],
    cs: ["advertising", "marketing", "branding", "ogilvy", "wpp", "dentsu", "publicis", "havas",
      "omnicom", "mccann", "leo burnett", "groupm", "group m", "madison world", "interpublic",
      "digital marketing agency", "social media agency", "pr agency", "public relation"],
    cw: ["agency:2", "communication:2", "brand:1.5", "media:1"],
  },
  {
    id: "customer",
    label: "Customer Success & Support",
    short: "Customer",
    emoji: "🎧",
    description: "Customer success, support, service, experience and implementation teams.",
    s: [
      "customer success", "customer success manager", "csm", "customer support", "customer service",
      "customer experience", "cx", "client success", "client service", "customer care",
      "support specialist", "support representative", "customer representative",
      "customer service representative", "call center", "call centre", "contact center",
      "implementation manager:8", "implementation specialist:8", "implementation consultant:7",
      "implementation engineer:8", "partner success", "solutions support",
      "chat support", "voice process", "customer support executive", "customer relationship manager:6",
      "atencion cliente", "servicio cliente", "kundenservice", "service client", "client relation",
      "client relationship", "onboarding specialist:6", "customer onboarding", "support engineer:3",
      "technical support:6", "customer delight", "escalation", "support executive", "support agent",
      "process associate:6", "process executive:6", "customer happiness", "guest experience:5",
      "account management:5", "client servicing", "client engagement",
    ],
    m: ["customer:5", "support:5", "onboarding:4", "bpo", "csr:5", "account manager:5", "helpline", "service:2"],
    w: ["client:3", "quality analyst:2"],
    cs: ["teleperformance", "concentrix", "sitel", "ttec", "startek", "bpo", "call center", "call centre",
      "alorica", "firstsource", "hinduja global", "sutherland", "conduent", "tech mahindra bpo",
      "transcom", "majorel", "wns", "genpact:3", "exl:3"],
  },
  {
    id: "hr",
    label: "HR & People",
    short: "HR",
    emoji: "🤝",
    description: "HR business partners, people ops, L&D, compensation and employee experience.",
    s: [
      "human resource", "hr", "hrbp", "hr business partner", "people operation", "people ops",
      "people partner", "people team", "people culture", "employee experience", "employee relation",
      "compensation", "benefit", "total reward", "payroll", "learning development", "lnd",
      "organizational development", "hris", "diversity equity inclusion", "dei", "labor relation",
      "industrial relation", "recursos humano", "rrhh", "ressources humaine", "personalreferent",
      "talent management", "talent development", "employer branding", "hr generalist",
      "hr executive", "hr manager", "hr intern", "people manager:4", "people lead", "head people",
      "people", "workforce management:6", "workforce planning", "hr operation", "hr admin",
      "employee engagement", "culture lead", "people analytic", "hr analyst", "hr consultant",
      "chief happiness officer", "wellbeing lead", "training coordinator:6", "training manager:7",
    ],
    m: ["diversity", "workforce", "culture:3", "wellbeing:3", "rh", "grh", "engagement:2"],
    cs: ["hr solution", "hr service", "hr consulting"],
  },
  {
    id: "project",
    label: "Project & Program Management",
    short: "Projects",
    emoji: "📋",
    description: "Project & program managers, PMO, scrum masters and delivery managers.",
    s: [
      "project manager", "project management", "program manager", "program management", "pmo",
      "scrum master", "agile coach", "delivery manager", "project coordinator", "program coordinator",
      "project lead", "project leader", "project director", "program director", "technical program manager",
      "pmp", "prince2", "project analyst", "project executive", "release manager:8", "delivery lead",
      "jefe proyecto", "gerente proyecto", "chef projet", "projektmanager", "projektleiter",
      "project officer", "project associate", "project management office", "portfolio management office",
      "program lead", "project controller", "project planner", "project control",
      "delivery head", "engagement lead:6", "iteration manager", "agile delivery",
    ],
    m: ["project", "agile", "scrum", "pm:4", "tpm:8", "implementation:3", "delivery:3"],
    w: ["program", "kanban", "planning:2", "jira"],
  },
  {
    id: "operations",
    label: "Operations, Supply Chain & Admin",
    short: "Operations",
    emoji: "🗂️",
    description: "Operations, supply chain, logistics, procurement, facilities and administration.",
    s: [
      "operation", "operations manager", "business operation", "bizops", "strategy operation:7",
      "supply chain", "logistic", "logistics", "procurement", "purchasing", "purchase manager",
      "vendor management", "vendor manager", "inventory", "warehouse", "fulfillment", "shipping",
      "freight", "fleet manager", "dispatcher", "demand planner", "supply planner", "production planner",
      "materials manager", "store keeper", "storekeeper", "import export", "exim", "administration",
      "office manager", "office administrator", "executive assistant", "personal assistant",
      "administrative assistant", "virtual assistant", "secretary", "receptionist", "clerk",
      "data entry", "back office", "facility", "facilities manager", "facility manager",
      "six sigma", "lean six sigma", "continuous improvement", "process excellence", "shift manager",
      "logistica", "logistique", "logistik", "compra", "compras", "achat", "einkauf", "buyer:6",
      "sourcing manager", "sourcing specialist:5", "category buyer", "planning manager",
      "process owner", "operational excellence", "business excellence", "admin executive",
      "admin manager", "administrative officer", "office assistant", "purchase executive", "purchase officer",
      "area manager:6", "city manager:6", "city head:6", "zonal manager:5", "regional manager:5", "cluster manager:5",
      "purchase:6",
      "documentation:6", "operations executive", "operations associate", "ops manager", "ops lead",
      "dispatch", "transport manager", "customs", "exports manager:4", "trade compliance", "mis coordinator",
      "management trainee:6", "general administration", "stores manager:4", "quality manager:5",
      "ehs", "hse", "health safety", "safety officer",
    ],
    m: ["administrator", "operator:5", "supervisor:5", "planner:4", "coordinator:3", "distribution:4",
      "delivery manager:3", "transportation:4", "material:3", "gerente:3", "coordinador:3",
      "coordinadora:3", "coordenador:3", "jefe:2", "maintenance:3", "procure", "vendor:4"],
    w: ["assistant:2.5", "team lead:2", "team leader:2", "process:1.5", "sourcing:3", "delivery:2.5"],
    x: ["manager:2", "officer:1.5", "lead:1", "specialist:1", "associate:1", "executive:1", "director:1", "incharge:1.5", "in charge:1.5"],
    cs: ["logistic", "logistics", "shipping", "freight", "supply chain", "warehouse", "warehousing",
      "cargo", "delhivery", "fedex", "dhl", "blue dart", "maersk", "ups", "xpressbee", "ecom express",
      "shadowfax", "flexport", "db schenker", "kuehne nagel", "c h robinson", "rivigo", "blackbuck",
      "porter", "dunzo", "shiprocket", "transport", "courier", "container"],
  },
  {
    id: "education",
    label: "Education & Academia",
    short: "Education",
    emoji: "🎓",
    description: "Professors, lecturers, teachers, tutors, trainers, coaches and school leaders.",
    s: [
      "professor:12", "assistant professor:12", "associate professor:12", "lecturer:11", "teacher:11", "tutor",
      "department academic mentor:8", "academic mentor:8",
      "faculty", "instructor", "educator", "teaching assistant", "teaching fellow", "dean",
      "school principal", "vice principal", "head teacher", "headmaster", "headmistress",
      "corporate trainer", "career coach", "career counselor", "academic advisor",
      "instructional designer", "librarian", "profesor", "profesora", "professeur", "docente",
      "maestro", "maestra", "lehrer", "lehrerin", "enseignant", "enseignante", "insegnante",
      "leraar", "hod", "content strategy:8", "head department", "education", "teaching", "academic", "academician",
      "edtech", "mentor:6", "subject matter expert education", "curriculum developer",
      "curriculum designer", "education counselor", "admission counselor", "admissions counselor",
      "school counselor", "principal school", "pgt", "tgt", "prt", "school teacher", "math teacher",
      "english teacher", "online tutor", "home tutor", "trainer:6", "coach:5", "training specialist:6",
      "learning specialist", "education consultant", "education officer", "registrar:5", "chancellor",
      "vice chancellor", "provost", "course instructor", "bootcamp instructor", "teach india fellow",
      "teach america", "facilitator:5", "soft skill trainer", "language trainer", "educational",
      "dean students:12", "learning consultant:8", "learning experience designer",
    ],
    m: ["curriculum", "counselor:5", "lecture", "tuition", "coaching", "principal:3", "learning:3", "school:3", "training:3"],
    w: ["fellow:2"],
    cs: ["school", "academy", "education", "edtech", "byjus", "byju", "unacademy", "upgrad", "coursera",
      "udemy", "khan academy", "teach india", "teach america", "vedantu", "physicswallah",
      "physics wallah", "simplilearn", "great learning", "scaler", "masai school", "newton school",
      "allen career institute", "aakash", "fiitjee", "chegg", "duolingo", "vidyalaya", "public school",
      "international school", "convent", "kendriya vidyalaya", "coaching", "tuition", "learning"],
    cm: ["university:2", "college:2", "institute:2", "iit:1", "iim:1.5", "nit:1", "bit:1", "polytechnic"],
  },
  {
    id: "students",
    label: "Students & Interns",
    short: "Students",
    emoji: "📚",
    description: "Students, new grads, interns and trainees without a more specific function.",
    s: [
      "student", "undergraduate", "undergrad", "graduate student", "mba candidate", "mba student",
      "btech", "b tech", "mtech", "m tech", "bsc", "b sc", "msc", "m sc", "bba", "bca", "mca", "pgdm",
      "final year", "sophomore", "freshman", "computer science student", "estudiante", "estudante",
      "etudiant", "etudiante", "studente", "alumno", "alumna", "aluno", "aluna", "studentin",
      "high school", "school student", "student ambassador", "campus ambassador", "master student",
      "masters student", "bachelor student", "law student", "medical student", "engineering student",
      "college student", "university student", "research student:4", "graduate school",
      "student intern", "student researcher:5", "student developer", "student member", "b e student",
      "be student", "bcom", "b com", "mcom", "m com", "ba student", "ma student", "12th", "class 12",
      "upsc aspiring:5", "ca student", "cs student", "cse student", "ece student", "it student",
      "new grad", "recent graduate", "fresh graduate", "graduated", "degree student", "phd aspirant",
      "b pharm", "bpharm", "m pharm", "llb student", "bdes", "b des", "barch", "b arch",
      "institute student mentor:12", "student mentor:12", "peer mentor", "co op:7", "campus representative",
      "executive member:6", "core team member:5", "core member:5", "overall coordinator:6", "core coordinator:6",
      "placement coordinator:9", "training placement associate:9", "training placement coordinator:9",
      "joint secretary:4", "general secretary:4", "additional secretary:4", "club member", "team member:2",
      "member:2", "associate member:3", "co organiser:4", "co organizer:4", "subcom member:5", "committee member:3",
      "developer student club:12", "student club", "gdsc", "student chapter", "student council", "student body",
      "student coordinator", "student volunteer", "student representative", "class representative",
      "gsoc", "google summer code", "hackathon:6", "competitive programmer:6", "leetcode:6",
    ],
    m: ["intern", "internship", "summer intern", "apprentice", "fresher", "pursuing:5", "mba:5",
      "learner:5", "bachelor", "master degree", "graduate:3.5", "trainee:3.5", "aspiring:3",
      "incoming:2.5", "alumnus:3", "alumni:3", "cse:3", "ece:3", "eee:3", "iit:2", "nit:2", "semester"],
    w: ["degree", "class", "batch", "junior:1"],
    cs: ["university student", "student", "student chapter", "student council", "student mentor program", "e cell",
      "entrepreneurship cell", "techfest", "mood indigo", "national service scheme", "nss", "gymkhana", "ccpd",
      "centre career planning development", "fsae", "formula student", "baja", "student body", "cultural committee",
      "placement cell", "training placement cell", "alumni council"],
    cm: ["university:2.5", "college:2.5", "institute technology:2.5", "iit", "nit", "iiit", "bits pilani",
      "vit", "srm", "manipal institute", "amity", "lpu", "iim", "isb", "school business:2",
      "institute management:2", "polytechnic", "stanford", "harvard", "mit", "berkeley", "carnegie mellon",
      "oxford", "cambridge"],
    cw: ["institute:2", "school:1.5", "academy:1", "club:3", "society:1.5", "racing:2", "fest:2"],
  },
  {
    id: "media",
    label: "Media, Arts & Entertainment",
    short: "Media & Arts",
    emoji: "🎬",
    description: "Journalists, writers, creators, artists, film, music, sports and entertainment.",
    s: [
      "journalist", "reporter", "editor", "writer", "author", "content writer", "content creator",
      "creator", "youtuber", "influencer", "blogger", "podcaster", "podcast", "photographer",
      "videographer", "video editor", "filmmaker", "film maker", "director photography",
      "cinematographer", "producer", "film producer", "music producer", "actor", "actress", "artist",
      "musician", "singer", "songwriter", "composer", "dancer", "painter", "animator", "vfx",
      "visual effect", "3d artist", "game artist", "anchor", "news anchor", "presenter",
      "radio jockey", "rj", "dj", "comedian", "stand up comedian", "fashion model", "entertainment",
      "journalism", "editorial", "copy editor", "publisher", "publishing", "broadcaster",
      "broadcasting", "screenwriter", "scriptwriter", "script writer", "poet", "novelist",
      "creative writer", "ghostwriter", "technical writer:8", "athlete", "professional athlete",
      "cricketer", "footballer", "sportsperson", "esport", "streamer", "curator", "theater",
      "voice artist", "voice over", "tattoo artist", "film director", "casting director",
      "music director", "creative producer", "art:6", "fine art", "sculptor", "illustrator artist",
      "periodista", "escritor", "escritora", "fotografo", "fotografa", "jornalista", "journaliste",
      "redakteur", "redakteurin", "schauspieler", "actor", "copy writer", "storyteller:6",
      "digital creator", "ugc creator", "social media influencer", "motivational speaker",
      "public speaker", "speaker:4", "sports", "sport", "cricket coach", "football coach",
      "film", "music", "media", "news", "documentary", "production house", "post production",
      "sound engineer", "audio engineer", "mixing engineer", "gamer", "game tester:6", "photojournalist",
      "stylist:6", "makeup artist:5", "model:5", "performer", "rapper", "guitarist", "pianist",
      "drummer", "choreographer", "art director film", "correspondent", "columnist", "news editor", "rapporteur:4",
    ],
    m: ["content:5", "creative:3", "gallery", "museum", "blog", "video", "photography", "podcast host", "host:4", "chess"],
    cs: ["studio", "film", "picture", "entertainment", "news", "magazine", "music", "publishing",
      "publisher", "broadcasting", "production", "tv", "television", "radio", "disney", "warner bro",
      "paramount", "sony picture", "universal music", "times internet", "bennett coleman",
      "hindustan time", "ndtv", "zee", "star india", "viacom18", "jiocinema", "dharma production",
      "yash raj", "t series", "bbc", "cnn", "new york time", "washington post", "guardian",
      "reuter", "times india", "the hindu", "indian express", "india today", "network18", "pocket fm",
      "kuku fm", "dream11", "mpl", "nazara", "ubisoft", "electronic art", "riot game", "epic game",
      "activision", "blizzard", "rockstar game", "bcci", "ipl", "fifa", "nba", "premier league"],
    cm: ["media", "times:2", "record:1.5", "creative:1.5", "art:2", "game:2", "gaming", "sport"],
  },
  {
    id: "public",
    label: "Government, Military & Nonprofit",
    short: "Public Sector",
    emoji: "🏛️",
    description: "Civil servants, policy, military, police, diplomats, NGOs and social impact.",
    s: [
      "government", "public sector", "civil servant", "civil service", "ias", "ips", "ifs", "irs",
      "ias officer", "bureaucrat", "diplomat", "consul", "politician", "member parliament", "mla",
      "senator", "congressman", "councillor", "councilor", "mayor", "public policy", "policy analyst",
      "policy advisor", "policy", "military", "army", "navy", "air force", "armed force", "soldier",
      "police", "police officer", "law enforcement", "firefighter", "nonprofit", "non profit", "ngo",
      "not profit", "social worker", "activist", "humanitarian", "fundraiser", "fundraising",
      "program officer", "grant writer", "united nation", "municipal", "public servant",
      "public administration", "foreign service", "legislative", "parliament", "customs officer",
      "tax inspector", "funcionario", "funcionaria", "servidor publico", "beamter", "beamtin",
      "social impact", "social sector", "development sector", "community development", "cadet",
      "ncc", "indian army", "indian navy", "indian air force", "defense", "veteran", "lieutenant",
      "captain:5", "colonel", "brigadier", "sergeant", "commander:5", "major general", "commissioner",
      "collector:5", "district magistrate", "sub inspector", "constable", "inspector:4", "gazetted officer",
      "section officer", "clerk government", "government official", "public health officer",
      "sustainability", "climate", "esg", "csr manager", "volunteer:6",
      "gandhi fellow", "sbi youth india fellow", "fellowship", "advocacy", "campaigner", "civic",
      "election", "upsc", "public affairs", "embassy", "ambassador:5",
    ],
    m: ["civil:2", "community:2", "social:3", "impact:3", "nation:2", "state:1", "federal:4", "welfare",
      "railway:4", "postal", "defence:6", "armed", "marine:3", "rural:3", "environmental:3", "csr:4",
      "fellow:2.5"],
    cs: ["government", "ministry", "department", "army", "navy", "air force", "police", "municipal",
      "council", "federal", "united nation", "unicef", "undp", "world bank", "imf", "ngo", "foundation",
      "nonprofit", "non profit", "red cross", "embassy", "consulate", "isro", "drdo", "indian railway",
      "nasa", "niti aayog", "reserve bank india", "rbi", "sebi", "federal reserve", "european commission",
      "gates foundation", "smile foundation", "akshaya patra", "who", "unesco", "unhcr", "world economic forum",
      "gouvernement", "gobierno", "corporation municipal", "public service commission", "high commission",
      "lok sabha", "rajya sabha", "state government", "central government", "city:2", "county:3", "commission:3",
      "authority:3", "board:1.5", "ncc", "crpf", "bsf", "cisf", "itbp", "coast guard", "cid", "cbi",
      "ministry defence", "ministry defense", "public sector", "psu", "trust:2", "society:2", "charity",
      "sewa", "seva", "mission:1.5", "welfare"],
  },
  {
    id: "real_estate",
    label: "Real Estate & Construction",
    short: "Real Estate",
    emoji: "🏗️",
    description: "Realtors, brokers, property managers, architects, construction and site engineers.",
    s: [
      "real estate", "realtor", "real estate agent", "property manager", "property consultant",
      "leasing", "leasing consultant", "estate agent", "construction", "construction manager",
      "site engineer:8", "site supervisor", "quantity surveyor", "surveyor", "civil contractor",
      "urban planner", "town planner", "landscape architect", "property valuer", "inmobiliaria",
      "bienes raice", "corretor", "immobilier", "immobilien", "makler", "architect:7",
      "architecture:6", "property", "real estate broker", "mortgage broker:6", "building contractor",
      "interior contractor", "estimation engineer", "billing engineer", "planning engineer:6",
      "project manager construction", "site manager", "construction engineer", "structural designer",
      "land acquisition", "property dealer", "channel sale real estate", "leasing manager",
      "asset manager real estate", "facility planner", "architectural", "architectural assistant", "estimator",
      "cost estimator", "quantity surveying",
    ],
    m: ["builder:5", "contractor:5", "interior:5", "estate", "site:3", "housing", "infra:3", "land:3"],
    w: ["broker:2", "developer project:3"],
    cs: ["realty", "real estate", "property", "realtor", "construction", "builder", "architect",
      "housing", "estate", "dlf", "godrej property", "lodha", "prestige group", "sobha", "brigade group",
      "cbre", "jll", "jones lang lasalle", "cushman wakefield", "knight frank", "colliers", "anarock",
      "nobroker", "magicbrick", "99acre", "housing com", "square yard", "zillow", "redfin", "compass",
      "keller williams", "re max", "remax", "coldwell banker", "century 21", "wework",
      "shapoorji pallonji", "afcons", "tata project", "gmr", "gvk", "nbcc", "dilip buildcon", "homes",
      "infrastructure:3", "infra:3", "developer:2", "infratech", "infraprojects", "constructions", "buildcon"],
  },
  {
    id: "services",
    label: "Hospitality, Retail & Trades",
    short: "Hospitality & Retail",
    emoji: "🛎️",
    description: "Hotels, restaurants, aviation crew, retail stores, fitness, beauty, drivers, trades and agriculture.",
    s: [
      "hospitality", "hotel", "hotelier", "restaurant", "chef", "cook", "sous chef", "pastry chef",
      "barista", "bartender", "waiter", "waitress", "steward", "stewardess", "flight attendant",
      "cabin crew", "air hostess", "pilot", "first officer:6", "commercial pilot", "airline pilot",
      "travel agent", "travel consultant", "tour guide", "tourism", "concierge", "front office",
      "housekeeping", "guest relation", "guest service", "store manager", "shop manager",
      "store associate", "cashier", "shopkeeper", "visual merchandiser", "salon", "hairstylist",
      "hair stylist", "barber", "beautician", "makeup artist:7", "fitness trainer", "personal trainer",
      "gym trainer", "fitness coach", "yoga trainer", "fitness instructor", "yoga instructor", "yoga teacher", "pilates instructor", "zumba",
      "fitness", "driver", "chauffeur", "delivery executive", "delivery partner", "delivery boy",
      "courier", "security guard", "electrician", "plumber", "carpenter", "mechanic", "janitor",
      "cleaner", "housekeeper", "caretaker", "wedding planner", "event planner:6", "catering",
      "food beverage", "fnb", "sommelier", "florist", "tailor", "jeweler", "farmer", "agriculture",
      "agricultural", "dairy", "poultry", "fisherman", "camarero", "cocinero", "chofer", "motorista",
      "cajero", "cajera", "koch", "kellner", "serveur", "serveuse", "cuisinier", "retail", "retail manager",
      "baker", "bakery", "cafe", "food blogger:5", "pet groomer", "dog trainer", "spa therapist",
      "nail artist", "welder:5", "painter house", "hvac technician:6", "technician field:4",
      "ground staff", "airport", "aviation", "airline", "air traffic controller", "flight dispatcher",
      "travel", "hotel management", "kitchen", "culinary", "food", "restaurant manager", "outlet manager",
      "franchise manager", "floor manager:5", "mall manager", "cinema", "gym", "yoga", "spa", "beauty",
      "salon manager", "store executive", "retail associate", "sales girl", "merchandiser:6",
      "security officer:5", "bouncer", "valet", "porter:5", "loader", "packer", "picker", "helper",
      "labour", "labor", "worker:3", "gardener", "maid", "nanny", "babysitter", "housewife:3", "homemaker:3",
    ],
    m: ["boutique", "grocery", "salon", "shop:4", "store:4", "server:3", "conductor:4", "technician:3"],
    cs: ["hotel", "resort", "restaurant", "cafe", "coffee", "kitchen", "airline", "airway", "aviation",
      "air india", "indigo", "emirates", "qatar airway", "lufthansa", "delta air", "united airline",
      "american airline", "southwest", "spicejet", "vistara", "akasa", "retail", "store", "mart",
      "supermarket", "hypermarket", "marriott", "hilton", "hyatt", "taj hotel", "ihcl", "oyo",
      "oberoi", "itc hotel", "accor", "ihg", "four season", "radisson", "starbuck", "mcdonald",
      "kfc", "domino", "walmart", "costco", "ikea", "reliance retail", "dmart", "avenue supermart",
      "big bazaar", "zara", "hnm", "decathlon", "uniqlo", "cult fit", "cultfit", "gold gym",
      "anytime fitness", "makemytrip", "booking com", "expedia", "thomas cook", "yatra", "salon",
      "spa", "gym", "fitness", "farm", "agro", "agri", "agriculture", "dairy", "bakery", "caterer",
      "hospitality", "travel", "tour", "rapido", "blinkit", "bigbasket", "jiomart", "nykaa store",
      "lenskart store", "tanishq", "titan", "trent", "westside", "pantaloon", "shoppers stop",
      "lifestyle international", "croma", "vijay sale", "haldiram", "barbeque nation", "burger king",
      "pizza hut", "subway restaurant", "chai point", "chaayos", "third wave coffee"],
    cm: ["food", "beverage", "fashion:2", "apparel:2", "jewel:3", "jeweler", "jewellery", "boutique", "salon"],
  },
  {
    id: "unspecified",
    label: "Role Not Shared",
    short: "Not Shared",
    emoji: "🔒",
    description: "Connections who left both job title and company blank on LinkedIn (or used a placeholder like “-”). There is nothing to classify.",
  },
];

// Industry/domain nouns describe *where* someone works rather than *what* they
// do. Their weight is capped so a role word in the same title wins:
// "Software Sales" → Sales, "Healthcare Recruiter" → Recruiters.
export const DOMAIN_CAPS: Record<string, number> = {
  software: 7, data: 7, api: 7, java: 7, python: 7, javascript: 7, typescript: 7, react: 7, golang: 7,
  php: 7, dotnet: 7, csharp: 7, cpp: 7, flutter: 7, kotlin: 7, django: 7, angular: 7, vue: 7, nodejs: 7,
  ios: 8, android: 8, web3: 7, cloud: 6, aws: 6, azure: 6, gcp: 6, kubernetes: 6, analytics: 8,
  "machine learning": 9, "artificial intelligence": 9, "big data": 8, "generative ai": 7, genai: 7,
  finance: 8, financial: 7, banking: 8, bank: 6, insurance: 7, tax: 8, audit: 8, fintech: 4, trading: 6,
  credit: 5, loan: 5, healthcare: 8, "health care": 8, medical: 7, clinical: 8, hospital: 6, pharma: 6,
  pharmaceutical: 6, biotech: 8, biotechnology: 8, "life science": 8, healthtech: 6, "health tech": 6,
  legal: 8, law: 6, compliance: 9, retail: 6, travel: 6, food: 6, hospitality: 8, fitness: 7, aviation: 7,
  airline: 6, airport: 6, kitchen: 6, cafe: 6, gym: 6, yoga: 6, spa: 6, beauty: 6, cinema: 6, media: 7,
  film: 7, music: 7, news: 6, sport: 7, sports: 7, entertainment: 7, art: 6, policy: 7, government: 8,
  military: 8, "real estate": 8, property: 6, construction: 8, architecture: 6, education: 7, teaching: 8,
  edtech: 6, educational: 6, academic: 7, brand: 7, communication: 8, advertising: 8, strategy: 8,
  manufacturing: 8, automotive: 8, electronics: 8, electronic: 8, semiconductor: 8, hardware: 8,
  embedded: 8, mechanical: 9, electrical: 9, civil: 9, chemical: 9, aerospace: 8, robotics: 8,
  operation: 8, logistic: 9, logistics: 9, procurement: 9, "supply chain": 9, people: 6, design: 9,
  ux: 9, ui: 9, sustainability: 7, climate: 6, esg: 7, quantum: 7, consulting: 9, consultancy: 9,
  advisory: 8, marketing: 10, product: 5, security: 5, it: 8, telecommunication: 8, agriculture: 7,
  agricultural: 7, dairy: 7, tourism: 7, fashion: 6, research: 6, dental: 8, pharmacy: 8, nursing: 8,
  veterinary: 8, social: 3, "public health": 8, "social impact": 7, "social sector": 7,
  "development sector": 7, nonprofit: 8, "non profit": 8, ngo: 8, defense: 8, payment: 5, crypto: 5,
};

export const CATEGORY_MAP: Record<CategoryId, CategoryDef> = Object.fromEntries(
  CATEGORIES.map((c) => [c.id, c]),
) as Record<CategoryId, CategoryDef>;

// ---------------------------------------------------------------------------
// Tags: cross-cutting labels that never compete with the primary category.

export const TAG_IDS = [
  "faang", "big_tech", "ai_lab", "yc", "big4", "mbb", "top_finance", "top_vc", "hiring", "open_to_work",
] as const;
export type TagId = (typeof TAG_IDS)[number];

export interface TagDef {
  id: TagId;
  label: string;
  emoji: string;
  description: string;
  /** Matched against the start of the company name ("Google Cloud India" ⊃ "google"). */
  companies?: string[];
  /** Company words that veto the tag, e.g. "Google Developer Student Club". */
  exclude?: string[];
  /** Phrases looked for anywhere in the job title (not the company). */
  titlePhrases?: string[];
}

export const TAGS: TagDef[] = [
  {
    id: "faang", label: "FAANG / MAANG", emoji: "🏆",
    description: "Meta, Apple, Amazon, Netflix, Google & Microsoft (incl. subsidiaries).",
    companies: ["meta", "facebook", "instagram", "whatsapp", "meta platform", "apple", "amazon", "aws",
      "amazon web service", "netflix", "google", "alphabet", "youtube", "google deepmind", "deepmind",
      "microsoft", "linkedin", "github", "waymo", "google cloud", "amazon development centre", "audible", "twitch"],
    exclude: ["student", "club", "community", "ambassador", "developer group", "champion", "mvp", "expert", "campus", "alumni", "certified", "partner", "reseller", "seller", "fellowship"],
  },
  {
    id: "big_tech", label: "Big Tech & Unicorns", emoji: "🦄",
    description: "Other large or high-growth tech companies.",
    companies: ["nvidia", "salesforce", "oracle", "adobe", "uber", "airbnb", "stripe", "tesla", "spacex",
      "ibm", "intel", "amd", "qualcomm", "cisco", "databricks", "snowflake", "atlassian", "shopify",
      "spotify", "twitter", "bytedance", "tiktok", "samsung", "paypal", "intuit", "servicenow", "workday",
      "vmware", "dropbox", "pinterest", "snap", "coinbase", "palantir", "doordash", "lyft", "zoom",
      "twilio", "cloudflare", "mongodb", "flipkart", "swiggy", "zomato", "razorpay", "paytm", "phonepe",
      "cred", "meesho", "zepto", "ola", "byju", "freshworks", "zoho", "postman", "browserstack", "canva",
      "revolut", "klarna", "plaid", "rippling", "deel", "figma", "notion", "ramp", "brex", "instacart",
      "reddit", "discord", "roblox", "sap", "booking com", "grab", "gojek", "shopee", "rakuten",
      "alibaba", "tencent", "baidu", "xiaomi", "huawei", "sony", "dell", "hp", "lenovo", "juspay", "groww",
      "zerodha", "unacademy", "dream11", "lenskart", "nykaa", "oyo", "delhivery", "sprinklr", "inmobi"],
    exclude: ["student", "club", "community", "ambassador", "partner", "reseller", "dealer", "distributor", "franchise", "store"],
  },
  {
    id: "ai_lab", label: "AI Labs", emoji: "🤖",
    description: "Frontier AI research labs and model companies.",
    companies: ["openai", "anthropic", "deepmind", "google deepmind", "mistral", "mistral ai", "xai",
      "cohere", "hugging face", "perplexity", "scale ai", "character ai", "inflection ai", "stability ai",
      "meta ai", "google brain", "ai21", "adept", "runway", "midjourney", "sarvam", "krutrim",
      "together ai", "safe superintelligence", "thinking machine"],
  },
  {
    id: "yc", label: "Y Combinator", emoji: "🟧",
    description: "People at YC or YC-backed startups (e.g. “Acme (YC W23)”).",
    companies: ["y combinator", "yc"],
    titlePhrases: ["y combinator", "yc"],
  },
  {
    id: "big4", label: "Big 4", emoji: "📊",
    description: "Deloitte, PwC, EY and KPMG.",
    companies: ["deloitte", "pwc", "pricewaterhousecooper", "price waterhouse", "ey", "ernst young", "kpmg", "ey gds",
      "ey parthenon", "monitor deloitte", "deloitte usi"],
  },
  {
    id: "mbb", label: "MBB Consulting", emoji: "🎩",
    description: "McKinsey, BCG and Bain & Company.",
    companies: ["mckinsey", "mckinsey company", "boston consulting group", "bcg", "bain company", "bain"],
    exclude: ["bain capital", "mckinsey capital"],
  },
  {
    id: "top_finance", label: "Wall Street & Top Finance", emoji: "💹",
    description: "Bulge-bracket banks, elite boutiques, top trading firms and asset managers.",
    companies: ["goldman sachs", "jpmorgan", "jp morgan", "jpmorgan chase", "morgan stanley", "bank america",
      "citi", "citibank", "citigroup", "barclays", "ubs", "deutsche bank", "credit suisse", "hsbc",
      "wells fargo", "blackrock", "lazard", "evercore", "jane street", "citadel", "two sigma", "de shaw",
      "d e shaw", "hudson river trading", "optiver", "tower research", "jump trading", "millennium",
      "bridgewater", "renaissance technology", "blackstone", "kkr", "carlyle", "apollo global",
      "centerview", "pjt partner", "moelis", "rothschild", "jefferies", "nomura", "bnp paribas", "imc trading",
      "susquehanna", "virtu", "akuna", "point72", "j p morgan", "jpmorganchase", "man group", "aqr", "fidelity", "vanguard"],
  },
  {
    id: "top_vc", label: "Top VC & Accelerators", emoji: "🌱",
    description: "Well-known venture firms and accelerators.",
    companies: ["sequoia", "sequoia capital", "peak xv", "andreessen horowitz", "a16z", "accel", "lightspeed",
      "benchmark capital", "greylock", "kleiner perkins", "index venture", "general catalyst", "tiger global",
      "softbank", "insight partner", "founders fund", "khosla venture", "bessemer", "matrix partner",
      "elevation capital", "nexus venture partner", "blume venture", "kalaari", "chiratae", "first round",
      "techstars", "500 global", "500 startup", "antler", "entrepreneur first", "y combinator", "yc",
      "google venture", "coatue", "thrive capital", "ribbit", "lux capital", "felicis", "redpoint",
      "battery venture", "iconiq", "dst global", "prosus", "naspers", "stellaris", "3one4", "prime venture"],
  },
  {
    id: "hiring", label: "Actively Hiring", emoji: "📢",
    description: "Mentions hiring in their title.",
    titlePhrases: ["hiring", "we hiring", "were hiring", "we re hiring", "now hiring"],
  },
  {
    id: "open_to_work", label: "Open to Work", emoji: "🔎",
    description: "Job seekers, aspiring roles and career breaks.",
    titlePhrases: ["open work", "seeking", "looking opportunity", "looking job", "looking new", "job seeker",
      "actively looking", "career break", "unemployed", "available immediately", "aspiring",
      "seeking opportunity", "open new opportunity", "immediate joiner", "between job", "in transition"],
  },
];

export const TAG_MAP: Record<TagId, TagDef> = Object.fromEntries(TAGS.map((t) => [t.id, t])) as Record<TagId, TagDef>;

// ---------------------------------------------------------------------------
// Seniority, derived from title words. Ordered from most to least senior.

export const SENIORITY_LEVELS = [
  "Founder", "C-Level", "VP", "Director / Head", "Manager / Lead", "Senior",
  "Mid-level", "Entry-level", "Intern", "Student", "Unknown",
] as const;
export type Seniority = (typeof SENIORITY_LEVELS)[number];

// Checked in this order within the primary title segment; first level found wins.
// "Product Manager Intern" is an Intern, "Assistant Manager" is a Manager.
// Phrases mapped to null only block shorter matches ("talent partner" is not a Partner).
export const SENIORITY_RULES: Array<{ level: Seniority | null; phrases: string[] }> = [
  { level: null, phrases: ["business partner", "talent partner", "channel partner", "delivery partner", "client partner", "people partner", "growth partner", "hiring partner", "lead generation", "lead gen", "head hunter", "headhunter", "team member", "chef", "sous chef", "staff nurse", "office staff", "chief happiness officer", "partner manager", "partnership", "product owner", "process owner", "founder office", "founders office", "office founder", "ceo office", "office ceo", "chief staff", "founding engineer", "founder residence", "entrepreneur residence", "founding member", "founding team"] },
  { level: "Founder", phrases: ["founder", "co founder", "owner", "business owner", "proprietor", "entrepreneur", "fundador", "fundadora", "fondateur", "grunder", "self employed", "solopreneur"] },
  { level: "Intern", phrases: ["intern", "internship", "summer analyst", "summer associate", "co op", "coop", "werkstudent", "stagiaire", "practicante", "estagiario"] },
  { level: "C-Level", phrases: ["ceo", "cto", "cfo", "coo", "cmo", "cio", "ciso", "cpo", "cro", "cdo", "cxo", "chro", "cco", "cso", "president", "managing director", "chairman", "chairperson", "general partner", "managing partner", "chief", "executive director", "director general", "geschaftsfuhrer", "pdg", "presidente", "md"] },
  { level: "VP", phrases: ["vp", "vice president", "vice presidente"] },
  { level: "Director / Head", phrases: ["director", "head", "partner", "principal", "dean", "hod", "directeur", "directora", "director general", "country manager", "general manager", "gm", "leiter"] },
  { level: "Manager / Lead", phrases: ["manager", "lead", "leader", "supervisor", "team lead", "tech lead", "scrum master", "gerente", "jefe", "responsable", "incharge", "in charge", "captain", "commander", "superintendent"] },
  { level: "Student", phrases: ["student", "undergraduate", "undergrad", "phd candidate", "phd student", "phd scholar", "btech", "b tech", "mba candidate", "estudiante", "estudante", "etudiant", "studente", "sophomore", "freshman", "final year", "pursuing", "research scholar", "doctoral candidate", "doctoral student", "aluno", "aluna", "alumno", "alumna"] },
  { level: "Senior", phrases: ["senior", "lead engineer", "lead data scientist", "lead designer", "senior staff", "staff engineer", "staff software engineer", "staff scientist", "staff designer", "staff analyst", "principal engineer", "principal scientist", "distinguished", "expert", "architect", "iii", "iv", "senior associate", "professor", "sme", "specialist ii"] },
  { level: "Entry-level", phrases: ["junior", "associate engineer", "associate software engineer", "trainee", "graduate", "fresher", "apprentice", "assistant", "entry level", "new grad", "junior associate", "graduate engineer trainee", "management trainee", "executive trainee", "probationary officer"] },
];
